require "plugins/plugins-setup"

require "core/options"
require "core/keymaps"
require "core/autocommands"
require "core/autoImpl"

-- 插件
require "plugins/lualine"
require "plugins/nvim-tree"
require "plugins/treesitter"
require "plugins/lsp"
require "plugins/cmp"
require "plugins/comment"
require "plugins/autopairs"
require "plugins/telescope"
require "plugins/tokyonight"
-- require "plugins/vscode"
require "plugins/markdown-preview"
require "plugins/treesitter-context"
require "plugins/symbols-outline"
require "plugins/hop"
require "plugins/gitsigns"
require "plugins/nvim-dap-cpp"
